version: '3.5'

services:
    code-feed-php:
        build:
            context: .
            dockerfile: .docker/php/local.Dockerfile
        expose:
            - 9000
        environment:
            PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
        env_file:
            - .env
        volumes:
            - .:/var/www/html
            - ~/.ssh/id_rsa:/root/.ssh/id_rsa
        container_name: code-feed-php
        networks:
            - code-feed-network
    code-feed-setup:
        depends_on:
            - code-feed-php
        build:
            context: .
            dockerfile: .docker/php/local.Dockerfile
        env_file:
            - .env
        volumes:
            - .:/var/www/html
        container_name: code-feed-setup
        networks:
            - code-feed-network
        command: /bin/bash -c
            "composer install &&
            php artisan migrate &&
            echo -e \"Setup done\"  "
    cloud-city-nginx:
        depends_on:
            - code-feed-setup
        image: nginx:1.23.0
        ports:
            - "80:80"
        environment:
            TZ: 'Europe/Belgrade'
        volumes:
            - ./:/var/www/html
            - .docker/nginx/local_default.conf:/etc/nginx/conf.d/default.conf
        container_name: code-feed-nginx
        networks:
            - code-feed-network
networks:
    code-feed-network:
        name: code-feed
        driver: bridge
