version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: code-feed:latest
    container_name: code-feed-web
    ports:
      - "8000:8000"
      - "5173:5173"
    volumes:
      - .:/var/www/html