version: "3.8"
services:
    php:
        container_name: code-feed-php
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - "8000:8000"
        networks:
            - code-feed
        security_opt:
            - no-new-privileges:true

    queue:
        container_name: code-feed-queue
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=queue
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - code-feed
        security_opt:
            - no-new-privileges:true

    node:
        container_name: code-feed-node
        build:
            context: .
            target: node
        volumes:
            - .:/usr/src
            - ./node_modules:/usr/src/node_modules
        tty: true
        networks:
            - code-feed
        security_opt:
            - no-new-privileges:true

    ollama:
        image: ollama/ollama
        container_name: code-feed-ollama
        ports:
            - "11434:11434"
        volumes:
            - ollama:/root/.ollama
            - ./Docker/ollama-entrypoint.sh:/usr/local/bin/entrypoint.sh
        networks:
            - code-feed
        entrypoint: /usr/local/bin/entrypoint.sh
        restart: unless-stopped

volumes:
    ollama:
        name: ollama

networks:
    code-feed:
        driver: bridge