<div>
    <x-turbine-ui-container
        class="whitespace-normal"
        variant="primary"
    >
    {!!nl2br(e($commit->change))!!}
    </x-turbine-ui-container>
    <x-turbine-ui-container
        class="whitespace-normal"
        variant="warning"
    >
        {!!nl2br(e($explanation))!!}
    </x-turbine-ui-container>
</div>
