name: Run tests and report coverage
on:
  push:

jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare The Environment
        run: cp .env.example .env
      - name: Install Composer Dependencies
        uses: php-actions/composer@v6
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build --if-present
      - name: Create Database
        run: touch database/database.sqlite
      - name: Run Migrations
        run: php artisan migrate
      - name: Run Tests
        run: php artisan test
        env:
          GOOGLE_AI_KEY: ${{ secrets.GOOGLE_AI_KEY }}
#        uses: php-actions/phpunit@v3
#        with:
#          php_extensions: "xdebug"
#          coverage_clover: "coverage/clover.xml"
#          args: --coverage-text
#        env:
#            XDEBUG_MODE: coverage
